/*
 * pcre2cpp - PCRE2 cpp wrapper
 *
 * Licensed under the BSD 3-Clause License with Attribution Requirement.
 * See the LICENSE file for details: https://github.com/MAIPA01/pcre2cpp/blob/main/LICENSE
 *
 * Copyright (c) 2025, Patryk Antosik (MAIPA01)
 *
 * PCRE2 library included in this project:
 * Copyright (c) 2016-2024, University of Cambridge.
 *
 * See the LICENSE_PCRE2 file for details: https://github.com/MAIPA01/pcre2cpp/blob/main/LICENSE_PCRE2
 */
#pragma once
#ifndef _PCRE2CPP_MATCH_ERROR_CODES_HPP_
	#define _PCRE2CPP_MATCH_ERROR_CODES_HPP_

	#include <pcre2cpp/config.hpp>

	#if !_PCRE2CPP_HAS_CXX17
_PCRE2CPP_ERROR("This is only available for c++17 and greater!");
	#else

		#include <pcre2cpp/types.hpp>

namespace pcre2cpp {
	enum class match_error_codes : int32_t {
		None	 = 1,					 // No error (default)
		NoMatch	 = PCRE2_ERROR_NOMATCH,	 // The subject string did not match the pattern.
		Partial	 = PCRE2_ERROR_PARTIAL,	 // The subject string did not match, but it did match partially.
		BadMagic = PCRE2_ERROR_BADMAGIC, /* PCRE2 stores a 4-byte "magic number" at the start of the compiled code,
											to catch the case when it is passed a junk pointer.
											This is the error that is returned when the magic number is not present
										 */
		BadMode =
		  PCRE2_ERROR_BADMODE,					 /* This error is given when a compiled pattern is passed
													to a function in a library of a different code unit width, for example,
													a pattern compiled by the 8-bit library is passed to a 16-bit or 32-bit library function.
												  */
		BadOffset	 = PCRE2_ERROR_BADOFFSET,	 // The value of startoffset was greater than the length of the subject.
		BadOption	 = PCRE2_ERROR_BADOPTION,	 // An unrecognized bit was set in the options argument.
		BadUTFOffset = PCRE2_ERROR_BADUTFOFFSET, /* The UTF code unit sequence that was passed as a subject was checked
													and found to be valid (the match_option::NoUTFCheck option was not set),
													but the value of startoffset did not point to the beginning of a
													UTF character or the end of the subject.
												  */
		Callout		 = PCRE2_ERROR_CALLOUT,		 /* This error is never generated by pcre2_match() itself.
													It is provided for use by callout functions that want to cause
													pcre2_match() or pcre2_callout_enumerate() to return a distinctive error code.
												  */
		DepthLimit	 = PCRE2_ERROR_DEPTHLIMIT,	 // The nested backtracking depth limit was reached.
		HeapLimit	 = PCRE2_ERROR_HEAPLIMIT,	 // The heap limit was reached.
		Internal =
		  PCRE2_ERROR_INTERNAL,						/* An unexpected internal error has occurred.
													   This error could be caused by a bug in PCRE2 or by overwriting of the compiled pattern.
													 */
		JITStackLimit = PCRE2_ERROR_JIT_STACKLIMIT, /* This error is returned when a pattern that was successfully
													   studied using JIT is being matched, but the memory available
													   for the just-in-time processing stack is not large enough.
													*/
		MatchLimit	  = PCRE2_ERROR_MATCHLIMIT,		// The backtracking match limit was reached.
		NoMemory	  = PCRE2_ERROR_NOMEMORY,		/* Heap memory is used to remember backtracking points.
													   This error is given when the memory allocation function (default or custom) fails.
													   Note that a different error, PCRE2_ERROR_HEAPLIMIT, is given if the amount of memory
													   needed exceeds the heap limit. match_error_codes::NoMemory is also returned
													   if match_options_bits::CopyMatchedSubject is set and memory allocation fails.
													 */
		Null		  = PCRE2_ERROR_NULL,			// Either the code, subject, or match_data argument was passed as nullptr.
		RecurseLoop =
		  PCRE2_ERROR_RECURSELOOP /* This error is returned when pcre2_match() detects a recursion loop within the pattern.
									 Specifically, it means that either the whole pattern or a capture group has been called
									 recursively for the second time at the same position in the subject string.
									 Some simple patterns that might do this are detected and faulted at compile time,
									 but more complicated cases, in particular mutual recursions between two different groups,
									 cannot be detected until matching is attempted.
								   */
	};
} // namespace pcre2cpp
	#endif
#endif